name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login docker registry
      run: echo Connext@0101 | docker login registry.connextpaas.com -u admin --password-stdin
      
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Show workdir
      run: pwd

    - name: Check maven installation
      run: mvn -version

    - name: Check maven installation
      run: java -version

    - uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: zulu
        
    - name: Build Proejct
      run: mvn clean package -Pbuild-image -Ppush-image

    - name: List images
      run: docker images

    - name: Push image
      run: docker push registry.connextpaas.com/piomin/employee-service:1.2-SNAPSHOT

    - name: Push image
      run: docker push registry.connextpaas.com/piomin/gateway-service:1.1-SNAPSHOT
    - name: Push image
      run: docker push registry.connextpaas.com/piomin/department-service:1.2-SNAPSHOT
    - name: Push image
      run: docker push registry.connextpaas.com/piomin/organization-service:1.2-SNAPSHOT
    - name: Push image
      run: docker push registry.connextpaas.com/piomin/discovery-service:1.1-SNAPSHOT
    - name: Push image
      run: docker push registry.connextpaas.com/piomin/config-service:1.1-SNAPSHOT
