name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Show workdir
      run: pwd

    - name: Check maven installation
      run: mvn -version

    - name: Check maven installation
      run: java -version

    - uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: zulu
        
    - name: Build Proejct
      run: mvn clean package -Pbuild-image

    - name: List images
      run: docker images
